/* eslint-disable */
// AUTO-GENERATED by scripts/parse-ai-tools.mjs from
// university_library_open_access_ai_tools_directory.md
// Do not edit by hand — re-run the script after updating the source markdown.

export interface AITool {
  id: string;
  name: string;
  category: string;
  group: string;
  description: string;
  audiences: string[];
  homepageUrl: string;
  imageUrl: string;
  accessCode: string;
  accessLabel: string;
  accessBadges: string[];
  accessText: string;
  accountRequired: boolean;
  integration: string;
  integrationTypes: string[];
  privacy: string;
  caution: string;
  verificationSource: string;
  lastVerified: string;
  tags: string[];
}

export const AI_TOOLS_SOURCE_DATE = '2026-09-25';

export const AI_TOOL_GROUPS: string[] = [
  "Scholarly Search & Discovery",
  "Literature Mapping & Discovery",
  "Scholarly Search & Evidence Synthesis",
  "Systematic Review & Evidence Screening",
  "Research Reading, PDF & Source-Grounded AI",
  "Academic Writing, Editing & Translation",
  "General-Purpose AI & AI Search",
  "Library Metadata, Cataloguing & Subject Indexing",
  "Open Scholarly Infrastructure & OA Resolution",
  "Digitisation, OCR, Speech & Accessibility",
  "Private / Local AI Infrastructure",
  "Data Science, Machine Learning & AI Development"
];

export const AI_TOOL_CATEGORIES: string[] = [
  "Scholarly & Patent Discovery",
  "Scholarly Search & Discovery",
  "Literature Mapping & Discovery",
  "Scholarly Search & Evidence Synthesis",
  "Systematic Review & Evidence Screening",
  "Document Q&A",
  "Research Reading & Comprehension",
  "Research Reading & Summarisation",
  "Research Reading & Writing",
  "Source-Grounded Research Workspace",
  "Academic Writing & Editing",
  "Grammar & Language Editing",
  "Language Editing & Translation",
  "Writing, Paraphrasing & Summarisation",
  "AI Search & Web Research",
  "General-Purpose AI Assistant",
  "Library Metadata, Classification & Subject Indexing",
  "Scholarly Document Parsing & Metadata Extraction",
  "Open Access Discovery & Infrastructure",
  "Open Access Resolution",
  "Open Scholarly Infrastructure",
  "Digitisation, Handwriting & OCR",
  "Digitisation, OCR & Accessibility",
  "Speech-to-Text & Accessibility",
  "Private / Local AI Infrastructure",
  "AI Development & Prototyping",
  "Data Science & Machine Learning",
  "Data Science, Machine Learning & GenAI",
  "Open AI Model & App Discovery"
];

export const AI_TOOL_AUDIENCES: string[] = [
  "Academic staff",
  "Accessibility teams",
  "Archives",
  "Archivists",
  "Bibliometricians",
  "Cataloguers",
  "Clinicians",
  "Data librarians",
  "Developers",
  "Digital humanities",
  "Digital librarians",
  "Editors",
  "Information scientists",
  "Information specialists",
  "Innovation offices",
  "Institutional AI teams",
  "International students",
  "Lecturers",
  "Librarians",
  "Libraries",
  "Library IT",
  "Metadata specialists",
  "Museums",
  "Oral-history projects",
  "Postgraduates",
  "Privacy-sensitive teams",
  "Repository developers",
  "Repository managers",
  "Repository staff",
  "Research software engineers",
  "Researchers",
  "Students",
  "Systematic reviewers",
  "Teaching staff"
];

export const AI_TOOLS: AITool[] = [
  {
    "id": "the-lens",
    "name": "The Lens",
    "category": "Scholarly & Patent Discovery",
    "group": "Scholarly Search & Discovery",
    "description": "Public scholarly and patent discovery platform linking scholarly works to patent literature. Useful for technology intelligence, prior-art exploration and research-to-innovation tracing.",
    "audiences": [
      "Researchers",
      "Librarians",
      "Innovation offices",
      "Information scientists"
    ],
    "homepageUrl": "https://www.lens.org/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=lens.org&sz=128",
    "accessCode": "OA-2 / Public access",
    "accessLabel": "Public access",
    "accessBadges": [
      "Free Service"
    ],
    "accessText": "Public scholarly search is available; some advanced/API uses may have separate conditions.",
    "accountRequired": true,
    "integration": "Link-out; institutional/API options subject to Lens terms.",
    "integrationTypes": [
      "External link",
      "API"
    ],
    "privacy": "Cloud service",
    "caution": "Not primarily a generative-AI assistant. Include it because its graph-based discovery and scholarly/patent linking are highly relevant to information practice.",
    "verificationSource": "https://support.lens.org/knowledge-base/scholarly-works-search/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Scholarly & Patent Discovery",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "semantic-scholar",
    "name": "Semantic Scholar",
    "category": "Scholarly Search & Discovery",
    "group": "Scholarly Search & Discovery",
    "description": "Free AI-powered academic search and discovery platform from Ai2. Uses machine learning for relevance, TLDR summaries, influential-citation signals, recommendations, research feeds and paper-level question answering on supported papers.",
    "audiences": [
      "Researchers",
      "Academic staff",
      "Librarians",
      "Students"
    ],
    "homepageUrl": "https://www.semanticscholar.org/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=semanticscholar.org&sz=128",
    "accessCode": "OA-1 / Free core service",
    "accessLabel": "Free core service",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Free and open to use; no login required for basic search; account adds library, feeds and alerts.",
    "accountRequired": false,
    "integration": "Link-out; REST API; downloadable scholarly graph/data resources.",
    "integrationTypes": [
      "External link",
      "API"
    ],
    "privacy": "Cloud service",
    "caution": "Full text is not guaranteed for every indexed paper; some links resolve to publisher paywalls. AI summaries must be verified against the paper.",
    "verificationSource": "https://www.semanticscholar.org/about/librarians",
    "lastVerified": "2026-09-25",
    "tags": [
      "Scholarly Search & Discovery",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "connected-papers",
    "name": "Connected Papers",
    "category": "Literature Mapping & Discovery",
    "group": "Literature Mapping & Discovery",
    "description": "Creates visual graphs of papers related to a seed article, helping users identify prior work, derivative work and clusters around a topic.",
    "audiences": [
      "Researchers",
      "Students",
      "Academic staff"
    ],
    "homepageUrl": "https://www.connectedpapers.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=connectedpapers.com&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free account tier with a monthly graph quota; paid plans remove/raise limits.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Graph similarity is not the same as relevance or methodological quality. Free quotas can change; verify before publishing limits in-app.",
    "verificationSource": "https://www.connectedpapers.com/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Literature Mapping & Discovery",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "inciteful",
    "name": "Inciteful",
    "category": "Literature Mapping & Discovery",
    "group": "Literature Mapping & Discovery",
    "description": "Citation-network discovery environment with Paper Discovery and Literature Connector workflows for finding important, similar and bridging papers across topics.",
    "audiences": [
      "Researchers",
      "Information scientists",
      "Academic staff"
    ],
    "homepageUrl": "https://incitefulmed.com/academic/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=incitefulmed.com&sz=128",
    "accessCode": "OA-2 / Open web tool",
    "accessLabel": "Open web tool",
    "accessBadges": [
      "Free Service"
    ],
    "accessText": "Public web access; academic discovery tools are available without a traditional subscription workflow.",
    "accountRequired": true,
    "integration": "Link-out; BibTeX export to reference managers.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Network analysis supports discovery but does not assess study validity or bias.",
    "verificationSource": "https://incitefulmed.com/academic/help/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Literature Mapping & Discovery",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "litmaps",
    "name": "Litmaps",
    "category": "Literature Mapping & Discovery",
    "group": "Literature Mapping & Discovery",
    "description": "Citation-based research discovery tool that visualises connections between papers and can help users expand a literature set beyond keyword-only searching.",
    "audiences": [
      "Researchers",
      "Postgraduates",
      "Academic staff"
    ],
    "homepageUrl": "https://www.litmaps.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=litmaps.com&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free plan available; advanced/larger projects require paid plans.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Use as a discovery aid. For reproducible evidence reviews, preserve search strategies from bibliographic databases as well.",
    "verificationSource": "https://www.litmaps.com/find-research-papers",
    "lastVerified": "2026-09-25",
    "tags": [
      "Literature Mapping & Discovery",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "researchrabbit",
    "name": "ResearchRabbit",
    "category": "Literature Mapping & Discovery",
    "group": "Literature Mapping & Discovery",
    "description": "Citation-based literature discovery and visual mapping tool. Helps users explore related papers, authors and citation networks, build collections, collaborate and import/export references.",
    "audiences": [
      "Researchers",
      "Postgraduates",
      "Librarians"
    ],
    "homepageUrl": "https://www.researchrabbit.ai/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=researchrabbit.ai&sz=128",
    "accessCode": "OA-2 / Free core workflow",
    "accessLabel": "Free core workflow",
    "accessBadges": [
      "Free Service"
    ],
    "accessText": "Free Forever tier with unlimited searches and collections; limits apply to seed-set size and advanced controls.",
    "accountRequired": true,
    "integration": "Link-out; Zotero/BibTeX-oriented workflows.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Excellent for discovery and citation chasing, but it should complement—not replace—database searching in systematic reviews.",
    "verificationSource": "https://www.researchrabbit.ai/pricing",
    "lastVerified": "2026-09-25",
    "tags": [
      "Literature Mapping & Discovery",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "consensus",
    "name": "Consensus",
    "category": "Scholarly Search & Evidence Synthesis",
    "group": "Scholarly Search & Evidence Synthesis",
    "description": "AI search engine for peer-reviewed research that answers natural-language research questions and links claims to papers. Includes paper search, limited Pro messages, study snapshots and limited deep reviews on its free tier.",
    "audiences": [
      "Researchers",
      "Academic staff",
      "Students",
      "Clinicians"
    ],
    "homepageUrl": "https://consensus.app/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=consensus.app&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free tier with unlimited basic paper searches and limited advanced AI usage.",
    "accountRequired": true,
    "integration": "Link-out; limited free API/MCP allowance may be available depending on plan.",
    "integrationTypes": [
      "External link",
      "API",
      "MCP"
    ],
    "privacy": "Cloud service",
    "caution": "AI-generated consensus/synthesis can oversimplify heterogeneous evidence; users should inspect included studies, methods and populations.",
    "verificationSource": "https://help.consensus.app/en/articles/10087865-subscription-plans",
    "lastVerified": "2026-09-25",
    "tags": [
      "Scholarly Search & Evidence Synthesis",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "elicit",
    "name": "Elicit",
    "category": "Scholarly Search & Evidence Synthesis",
    "group": "Scholarly Search & Evidence Synthesis",
    "description": "AI research assistant for finding papers, generating structured summaries, chatting with accessible full text, extracting information and supporting literature-review workflows.",
    "audiences": [
      "Researchers",
      "Postgraduates",
      "Academic staff"
    ],
    "homepageUrl": "https://elicit.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=elicit.com&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Meaningful free Basic tier; unlimited search/summaries with limited advanced-agent/report usage.",
    "accountRequired": true,
    "integration": "Link-out. API is not part of the free individual tier.",
    "integrationTypes": [
      "External link",
      "API"
    ],
    "privacy": "Cloud service",
    "caution": "Do not treat generated synthesis as a systematic-review substitute. Verify extracted values, eligibility decisions and citations.",
    "verificationSource": "https://elicit.com/pricing",
    "lastVerified": "2026-09-25",
    "tags": [
      "Scholarly Search & Evidence Synthesis",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "asreview-lab",
    "name": "ASReview LAB",
    "category": "Systematic Review & Evidence Screening",
    "group": "Systematic Review & Evidence Screening",
    "description": "Fully open-source AI-aided screening software using active learning to prioritise records in systematic reviews while keeping the human reviewer in control.",
    "audiences": [
      "Researchers",
      "Information specialists",
      "Systematic reviewers"
    ],
    "homepageUrl": "https://asreview.nl/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=asreview.nl&sz=128",
    "accessCode": "OA-1 / Open source",
    "accessLabel": "Open source",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Free, open source, no subscription fee; local/server/Docker deployment.",
    "accountRequired": true,
    "integration": "Self-host; link-out; local install; server deployment.",
    "integrationTypes": [
      "External link",
      "Self-host"
    ],
    "privacy": "Local / self-hostable",
    "caution": "AI prioritisation does not retrieve records that were absent from the original search set. Document stopping rules and human decisions for reproducibility.",
    "verificationSource": "https://asreview.nl/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Systematic Review & Evidence Screening",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "rayyan",
    "name": "Rayyan",
    "category": "Systematic Review & Evidence Screening",
    "group": "Systematic Review & Evidence Screening",
    "description": "Systematic-review platform for reference import, screening, deduplication, collaboration and evidence-synthesis workflows. Its free tier includes core review functionality and limited AI-assisted relevance features.",
    "audiences": [
      "Researchers",
      "Systematic reviewers",
      "Academic staff"
    ],
    "homepageUrl": "https://www.rayyan.ai/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=rayyan.ai&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free forever basic plan; advanced AI features and larger workflows are paid.",
    "accountRequired": true,
    "integration": "Link-out; institutional/API features are paid.",
    "integrationTypes": [
      "External link",
      "API"
    ],
    "privacy": "Cloud service",
    "caution": "Clearly label which AI features are free versus premium; current free-plan capabilities should be rechecked periodically.",
    "verificationSource": "https://www.rayyan.ai/pricing",
    "lastVerified": "2026-09-25",
    "tags": [
      "Systematic Review & Evidence Screening",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "chatpdf",
    "name": "ChatPDF",
    "category": "Document Q&A",
    "group": "Research Reading, PDF & Source-Grounded AI",
    "description": "Conversational document tool that answers questions about uploaded PDFs and other document formats, with source-linked responses intended to support verification.",
    "audiences": [
      "Researchers",
      "Students",
      "Librarians",
      "Academic staff"
    ],
    "homepageUrl": "https://www.chatpdf.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=chatpdf.com&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free plan currently allows limited document analysis per day; no account is required to start.",
    "accountRequired": false,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Do not upload confidential, embargoed, copyrighted, personal or research-participant data unless institutional policy and vendor terms allow it.",
    "verificationSource": "https://www.chatpdf.com/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Document Q&A",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "humata",
    "name": "Humata",
    "category": "Document Q&A",
    "group": "Research Reading, PDF & Source-Grounded AI",
    "description": "AI document-analysis and question-answering tool for uploaded files. Useful for extracting and explaining information from long documents.",
    "audiences": [
      "Researchers",
      "Academic staff",
      "Librarians"
    ],
    "homepageUrl": "https://www.humata.ai/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=humata.ai&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free tier with a monthly page allowance; paid tiers raise limits and security controls.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Free-tier security controls are not the same as enterprise controls. Avoid sensitive or unpublished material unless terms are acceptable.",
    "verificationSource": "https://www.humata.ai/pricing",
    "lastVerified": "2026-09-25",
    "tags": [
      "Document Q&A",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "explainpaper",
    "name": "Explainpaper",
    "category": "Research Reading & Comprehension",
    "group": "Research Reading, PDF & Source-Grounded AI",
    "description": "AI paper-reading assistant that explains highlighted passages, supports follow-up questions and can import a Zotero library.",
    "audiences": [
      "Students",
      "Researchers",
      "Academic staff"
    ],
    "homepageUrl": "https://www.explainpaper.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=explainpaper.com&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free plan available indefinitely with basic models and unlimited highlight explanations; advanced models/summaries are paid.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Useful for comprehension, not authoritative interpretation. Mathematical/technical explanations can still be wrong.",
    "verificationSource": "https://www.explainpaper.com/pricing",
    "lastVerified": "2026-09-25",
    "tags": [
      "Research Reading & Comprehension",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "scholarcy",
    "name": "Scholarcy",
    "category": "Research Reading & Summarisation",
    "group": "Research Reading, PDF & Source-Grounded AI",
    "description": "Research-document summariser that extracts key points into structured summaries/flashcards and supports reading and synthesis workflows.",
    "audiences": [
      "Researchers",
      "Students",
      "Editors"
    ],
    "homepageUrl": "https://www.scholarcy.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=scholarcy.com&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free Article Summarizer with usage limits; paid plan adds unlimited summaries, collections and literature matrices.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Summaries are secondary representations; users should consult original methods, results and limitations before citing.",
    "verificationSource": "https://www.scholarcy.com/pricing",
    "lastVerified": "2026-09-25",
    "tags": [
      "Research Reading & Summarisation",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "scispace",
    "name": "SciSpace",
    "category": "Research Reading & Writing",
    "group": "Research Reading, PDF & Source-Grounded AI",
    "description": "End-to-end research platform with literature discovery, chat-with-PDF, literature-review, writing, paraphrasing and citation-oriented tools.",
    "audiences": [
      "Researchers",
      "Students",
      "Academic staff",
      "Editors"
    ],
    "homepageUrl": "https://scispace.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=scispace.com&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free access exists for several research/writing features, but advanced usage is credit/plan limited.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Do not market the entire premium research suite as free. Users should verify citations and avoid undisclosed AI-generated manuscript text where prohibited.",
    "verificationSource": "https://scispace.com/pricing",
    "lastVerified": "2026-09-25",
    "tags": [
      "Research Reading & Writing",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "gemini-notebook",
    "name": "Gemini Notebook (formerly NotebookLM)",
    "category": "Source-Grounded Research Workspace",
    "group": "Research Reading, PDF & Source-Grounded AI",
    "description": "Google source-grounded AI notebook for asking questions across uploaded/linked sources and generating reports, study aids, audio/video overviews, mind maps and other learning artifacts.",
    "audiences": [
      "Researchers",
      "Academic staff",
      "Students",
      "Librarians"
    ],
    "homepageUrl": "https://notebooklm.google.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=notebooklm.google.com&sz=128",
    "accessCode": "OA-2 / Free standard tier",
    "accessLabel": "Free standard tier",
    "accessBadges": [
      "Free Service"
    ],
    "accessText": "Standard tier is free with a Google account; quotas apply.",
    "accountRequired": true,
    "integration": "Link-out; institutional Workspace deployment may provide stronger governance.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "For university use, prefer managed Education/Workspace accounts where possible. Outputs should be checked against the source set.",
    "verificationSource": "https://support.google.com/gemininotebook/answer/16213268?hl=en",
    "lastVerified": "2026-09-25",
    "tags": [
      "Source-Grounded Research Workspace",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "paperpal",
    "name": "Paperpal",
    "category": "Academic Writing & Editing",
    "group": "Academic Writing, Editing & Translation",
    "description": "Academic writing assistant offering language correction, generative writing support, paraphrasing, academic tone adjustment and submission-readiness checks.",
    "audiences": [
      "Researchers",
      "Academic staff",
      "Editors",
      "Students"
    ],
    "homepageUrl": "https://paperpal.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=paperpal.com&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free version includes a monthly language-suggestion quota and limited daily AI uses.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Users remain responsible for authorship, disclosure, originality and citation accuracy. Never use paraphrasing to conceal plagiarism.",
    "verificationSource": "https://support.paperpal.com/support/solutions/articles/3000126442-can-i-use-paperpal-for-free-",
    "lastVerified": "2026-09-25",
    "tags": [
      "Academic Writing & Editing",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "trinka",
    "name": "Trinka",
    "category": "Academic Writing & Editing",
    "group": "Academic Writing, Editing & Translation",
    "description": "Academic/technical writing assistant with grammar correction, paraphrasing, consistency support, AI writing, citation tools and journal-oriented checks.",
    "audiences": [
      "Researchers",
      "Academic staff",
      "Editors",
      "Students"
    ],
    "homepageUrl": "https://www.trinka.ai/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=trinka.ai&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free Basic plan with monthly limits; paid tiers add expanded writing, privacy and integrity features.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "The free plan has standard—not confidential—data handling. Sensitive manuscripts should follow institutional data-handling rules.",
    "verificationSource": "https://www.trinka.ai/pricing",
    "lastVerified": "2026-09-25",
    "tags": [
      "Academic Writing & Editing",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "languagetool",
    "name": "LanguageTool",
    "category": "Grammar & Language Editing",
    "group": "Academic Writing, Editing & Translation",
    "description": "Multilingual grammar, spelling and style assistant. Useful for polishing academic and professional prose.",
    "audiences": [
      "Editors",
      "Researchers",
      "Academic staff",
      "Students"
    ],
    "homepageUrl": "https://languagetool.org/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=languagetool.org&sz=128",
    "accessCode": "OA-2/3 / Free + premium",
    "accessLabel": "Free + premium",
    "accessBadges": [
      "Free Service"
    ],
    "accessText": "Free services are available; premium offers expanded checks and limits.",
    "accountRequired": true,
    "integration": "Link-out; self-host/open-source components may be considered separately subject to current licensing.",
    "integrationTypes": [
      "External link",
      "Self-host"
    ],
    "privacy": "Local / self-hostable",
    "caution": "Grammar recommendations are not discipline-specific peer review; domain terminology and authorial meaning require human review.",
    "verificationSource": "https://languagetool.org/legal/terms",
    "lastVerified": "2026-09-25",
    "tags": [
      "Grammar & Language Editing",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "deepl-write",
    "name": "DeepL Write",
    "category": "Language Editing & Translation",
    "group": "Academic Writing, Editing & Translation",
    "description": "AI writing assistant for improving grammar, wording, style and clarity; pairs naturally with DeepL Translator for multilingual academic communication.",
    "audiences": [
      "Editors",
      "Researchers",
      "Academic staff",
      "International students"
    ],
    "homepageUrl": "https://www.deepl.com/write",
    "imageUrl": "https://www.google.com/s2/favicons?domain=deepl.com&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free web version available with character limits; Pro offers stronger data protection and larger limits.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "DeepL states that free-service content may be processed to improve its systems. Do not send confidential or unpublished material through the free tier.",
    "verificationSource": "https://support.deepl.com/hc/en-us/articles/6318834492700-About-DeepL-Write",
    "lastVerified": "2026-09-25",
    "tags": [
      "Language Editing & Translation",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "quillbot",
    "name": "QuillBot",
    "category": "Writing, Paraphrasing & Summarisation",
    "group": "Academic Writing, Editing & Translation",
    "description": "AI writing suite with paraphrasing, grammar checking, summarisation, translation and chat features.",
    "audiences": [
      "Students",
      "Researchers",
      "Editors",
      "Academic staff"
    ],
    "homepageUrl": "https://quillbot.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=quillbot.com&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Many tools have a free tier with input/output limits; premium removes or raises limits.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Library guidance should explicitly state that paraphrasing does not remove the need to cite sources and should not be used to evade plagiarism or AI-use policies.",
    "verificationSource": "https://help.quillbot.com/hc/en-us/articles/4405586576535-How-do-I-use-Quillbot-for-free",
    "lastVerified": "2026-09-25",
    "tags": [
      "Writing",
      "Paraphrasing & Summarisation",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "perplexity",
    "name": "Perplexity",
    "category": "AI Search & Web Research",
    "group": "General-Purpose AI & AI Search",
    "description": "AI answer/search engine that synthesises web results and provides citations. Useful for exploratory searching, current-awareness scanning and source discovery.",
    "audiences": [
      "Researchers",
      "Librarians",
      "Academic staff",
      "Students"
    ],
    "homepageUrl": "https://www.perplexity.ai/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=perplexity.ai&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free Standard plan with practically unlimited basic searches and limited advanced searches/file uploads.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Citation presence does not guarantee that a cited source supports every generated claim. Users must open and assess the sources.",
    "verificationSource": "https://www.perplexity.ai/help-center/en/articles/11187416-which-perplexity-subscription-plan-is-right-for-you",
    "lastVerified": "2026-09-25",
    "tags": [
      "AI Search & Web Research",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "chatgpt",
    "name": "ChatGPT",
    "category": "General-Purpose AI Assistant",
    "group": "General-Purpose AI & AI Search",
    "description": "General AI assistant for brainstorming, explanation, summarisation, web research, file analysis, coding and multimodal tasks. The free tier includes a range of tools with usage limits.",
    "audiences": [
      "Librarians",
      "Researchers",
      "Academic staff",
      "Editors",
      "Students"
    ],
    "homepageUrl": "https://chatgpt.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=chatgpt.com&sz=128",
    "accessCode": "OA-2/3 / Free tier",
    "accessLabel": "Free tier",
    "accessBadges": [
      "Free Service"
    ],
    "accessText": "Free tier available; higher limits and capabilities on paid plans.",
    "accountRequired": true,
    "integration": "Link-out; API usage is separately billed and should not be assumed free.",
    "integrationTypes": [
      "External link",
      "API"
    ],
    "privacy": "Cloud service",
    "caution": "Can generate false or fabricated information. Require source verification, transparent AI-use practices and protection of sensitive institutional/research data.",
    "verificationSource": "https://help.openai.com/en/articles/9275245-chatgpt-free-tier-faq",
    "lastVerified": "2026-09-25",
    "tags": [
      "General-Purpose AI Assistant",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "claude",
    "name": "Claude",
    "category": "General-Purpose AI Assistant",
    "group": "General-Purpose AI & AI Search",
    "description": "Anthropic AI assistant for writing, document analysis, coding, data work and web-enabled research tasks.",
    "audiences": [
      "Researchers",
      "Academic staff",
      "Editors",
      "Librarians"
    ],
    "homepageUrl": "https://claude.ai/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=claude.ai&sz=128",
    "accessCode": "OA-2/3 / Free tier",
    "accessLabel": "Free tier",
    "accessBadges": [
      "Free Service"
    ],
    "accessText": "Free plan available with limited usage; paid plans provide more capacity and research/project features.",
    "accountRequired": true,
    "integration": "Link-out; API is separately billed.",
    "integrationTypes": [
      "External link",
      "API"
    ],
    "privacy": "Cloud service",
    "caution": "Availability varies by supported region. Treat generated claims as unverified until checked against primary or authoritative sources.",
    "verificationSource": "https://www.anthropic.com/pricing?subjects=claude&type=product",
    "lastVerified": "2026-09-25",
    "tags": [
      "General-Purpose AI Assistant",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "google-gemini",
    "name": "Google Gemini",
    "category": "General-Purpose AI Assistant",
    "group": "General-Purpose AI & AI Search",
    "description": "Google multimodal AI assistant for research support, writing, coding, analysis and web-connected tasks.",
    "audiences": [
      "Researchers",
      "Academic staff",
      "Students",
      "Librarians"
    ],
    "homepageUrl": "https://gemini.google.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=gemini.google.com&sz=128",
    "accessCode": "OA-2/3 / Free tier",
    "accessLabel": "Free tier",
    "accessBadges": [
      "Free Service"
    ],
    "accessText": "Free access with compute-based limits; paid Google AI plans increase limits.",
    "accountRequired": true,
    "integration": "Link-out.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "For institutional data, distinguish personal-account usage from managed Google Workspace/Education usage and apply university policy.",
    "verificationSource": "https://support.google.com/gemini/answer/16275805?hl=en",
    "lastVerified": "2026-09-25",
    "tags": [
      "General-Purpose AI Assistant",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "microsoft-copilot",
    "name": "Microsoft Copilot",
    "category": "General-Purpose AI Assistant",
    "group": "General-Purpose AI & AI Search",
    "description": "Microsoft AI assistant for web questions, writing, summarisation, file-related tasks and image creation, with deeper integration available in Microsoft 365 products.",
    "audiences": [
      "Academic staff",
      "Librarians",
      "Researchers",
      "Students"
    ],
    "homepageUrl": "https://copilot.microsoft.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=copilot.microsoft.com&sz=128",
    "accessCode": "OA-2/3 / Free core",
    "accessLabel": "Free core",
    "accessBadges": [
      "Free Service"
    ],
    "accessText": "Core Copilot web/app chat is available free; advanced Microsoft 365 integration requires qualifying subscriptions.",
    "accountRequired": true,
    "integration": "Link-out; institution-specific M365 integration depends on licensing.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Do not imply that paid Microsoft 365 Copilot capabilities are included in the free web experience.",
    "verificationSource": "https://support.microsoft.com/en-us/Microsoft-365-Copilot/what-s-the-difference-between-microsoft-copilot-free-and-copilot-in-microsoft-365",
    "lastVerified": "2026-09-25",
    "tags": [
      "General-Purpose AI Assistant",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "annif",
    "name": "Annif",
    "category": "Library Metadata, Classification & Subject Indexing",
    "group": "Library Metadata, Cataloguing & Subject Indexing",
    "description": "Open-source automated subject-indexing and classification toolkit developed mainly at the National Library of Finland. Supports controlled vocabularies, multilingual workflows, web UI, CLI and REST API.",
    "audiences": [
      "Librarians",
      "Cataloguers",
      "Metadata specialists",
      "Archives",
      "Museums"
    ],
    "homepageUrl": "https://annif.org/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=annif.org&sz=128",
    "accessCode": "OA-1 / Open source",
    "accessLabel": "Open source",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Free and open source (Apache 2.0 core); self-hostable.",
    "accountRequired": true,
    "integration": "High-value native integration candidate; REST API and Docker/PyPI deployment.",
    "integrationTypes": [
      "API"
    ],
    "privacy": "Cloud service",
    "caution": "Model quality depends on vocabulary, language technology and training corpus. Human cataloguer validation is essential.",
    "verificationSource": "https://annif.org/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Library Metadata",
      "Classification & Subject Indexing",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "finto-ai",
    "name": "Finto AI",
    "category": "Library Metadata, Classification & Subject Indexing",
    "group": "Library Metadata, Cataloguing & Subject Indexing",
    "description": "Free National Library of Finland service built on Annif. Suggests controlled subject headings from text and exposes an open API.",
    "audiences": [
      "Librarians",
      "Metadata specialists",
      "Repository managers",
      "Students"
    ],
    "homepageUrl": "https://ai.finto.fi/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=ai.finto.fi&sz=128",
    "accessCode": "OA-1 / Free public service",
    "accessLabel": "Free public service",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "No payment required; public web UI and API.",
    "accountRequired": true,
    "integration": "Strong demonstration/integration candidate for automated subject suggestion.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Current vocabularies/languages are oriented to Finto/YSO contexts; assess vocabulary fit before applying in a Nigerian university library.",
    "verificationSource": "https://www.kansalliskirjasto.fi/en/services/finto-ai",
    "lastVerified": "2026-09-25",
    "tags": [
      "Library Metadata",
      "Classification & Subject Indexing",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "grobid",
    "name": "GROBID",
    "category": "Scholarly Document Parsing & Metadata Extraction",
    "group": "Library Metadata, Cataloguing & Subject Indexing",
    "description": "Open-source machine-learning library for extracting and structuring bibliographic metadata, references and full scholarly-document structure from PDFs into TEI/XML.",
    "audiences": [
      "Digital librarians",
      "Repository developers",
      "Information scientists",
      "Editors"
    ],
    "homepageUrl": "https://github.com/grobidOrg/grobid",
    "imageUrl": "https://www.google.com/s2/favicons?domain=github.com&sz=128",
    "accessCode": "OA-1 / Open source",
    "accessLabel": "Open source",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Free and open source under Apache 2.0.",
    "accountRequired": true,
    "integration": "Excellent backend component for repository ingestion, metadata extraction and reference parsing.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Requires technical deployment and quality assurance; extraction accuracy varies with PDF quality and layout.",
    "verificationSource": "https://github.com/grobidOrg/grobid",
    "lastVerified": "2026-09-25",
    "tags": [
      "Scholarly Document Parsing & Metadata Extraction",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "core",
    "name": "CORE",
    "category": "Open Access Discovery & Infrastructure",
    "group": "Open Scholarly Infrastructure & OA Resolution",
    "description": "Large aggregation of open-access research metadata and full text. Supports discovery and machine access that can power repository search, recommender and text-mining services.",
    "audiences": [
      "Librarians",
      "Developers",
      "Researchers",
      "Repository managers"
    ],
    "homepageUrl": "https://core.ac.uk/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=core.ac.uk&sz=128",
    "accessCode": "OA-1/4 / OA corpus + API",
    "accessLabel": "OA corpus + API",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Open-access search; API access is available with registration/usage conditions.",
    "accountRequired": true,
    "integration": "Good candidate for native OA discovery and full-text linking.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Respect API terms and licensing of individual full-text documents; open availability does not imply unrestricted reuse of every work.",
    "verificationSource": "https://core.ac.uk/services/api",
    "lastVerified": "2026-09-25",
    "tags": [
      "Open Access Discovery & Infrastructure",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "unpaywall",
    "name": "Unpaywall",
    "category": "Open Access Resolution",
    "group": "Open Scholarly Infrastructure & OA Resolution",
    "description": "Open database/service for finding legal open-access locations for DOI-identified scholarly works. Valuable as an 'Find Open Copy' resolver inside a library app.",
    "audiences": [
      "Librarians",
      "Researchers",
      "Developers"
    ],
    "homepageUrl": "https://unpaywall.org/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=unpaywall.org&sz=128",
    "accessCode": "OA-1 / Free OA-resolution API",
    "accessLabel": "Free OA-resolution API",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Free API access; current service directs general search use toward OpenAlex.",
    "accountRequired": true,
    "integration": "Excellent native integration for DOI-level OA links; follow current API guidance.",
    "integrationTypes": [
      "API"
    ],
    "privacy": "Cloud service",
    "caution": "Its general search endpoint was retired in September 2026; use OpenAlex for broad work search and Unpaywall-style OA fields for DOI resolution.",
    "verificationSource": "https://data.unpaywall.org/products/api",
    "lastVerified": "2026-09-25",
    "tags": [
      "Open Access Resolution",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "openalex",
    "name": "OpenAlex",
    "category": "Open Scholarly Infrastructure",
    "group": "Open Scholarly Infrastructure & OA Resolution",
    "description": "Open scholarly knowledge graph covering works, authors, sources, institutions, topics and citations. Useful for discovery, bibliometrics, repository enrichment and building library research services.",
    "audiences": [
      "Librarians",
      "Developers",
      "Bibliometricians",
      "Researchers"
    ],
    "homepageUrl": "https://openalex.org/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=openalex.org&sz=128",
    "accessCode": "OA-1 / Open data + free API",
    "accessLabel": "Open data + free API",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Open data; basic API use is free, with a free key increasing the daily budget.",
    "accountRequired": true,
    "integration": "Strong candidate for native integration through REST API.",
    "integrationTypes": [
      "API"
    ],
    "privacy": "Cloud service",
    "caution": "API economics/rate limits can change; cache responses and display provenance. Bibliometric indicators require contextual interpretation.",
    "verificationSource": "https://help.openalex.org/api/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Open Scholarly Infrastructure",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "transkribus",
    "name": "Transkribus",
    "category": "Digitisation, Handwriting & OCR",
    "group": "Digitisation, OCR, Speech & Accessibility",
    "description": "AI platform for handwritten and printed text recognition, custom model training and document editing; designed heavily around cultural-heritage and archival material.",
    "audiences": [
      "Libraries",
      "Archives",
      "Researchers",
      "Digital humanities"
    ],
    "homepageUrl": "https://www.transkribus.org/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=transkribus.org&sz=128",
    "accessCode": "OA-3 / Freemium",
    "accessLabel": "Freemium",
    "accessBadges": [
      "Freemium"
    ],
    "accessText": "Free plan with monthly recognition credits; paid plans add credits and advanced models.",
    "accountRequired": true,
    "integration": "Link-out; API/institutional deployment options are generally paid.",
    "integrationTypes": [
      "External link",
      "API"
    ],
    "privacy": "Cloud service",
    "caution": "Credit limits apply. Check data-location/privacy requirements before uploading sensitive archival or restricted materials.",
    "verificationSource": "https://www.transkribus.org/pricing",
    "lastVerified": "2026-09-25",
    "tags": [
      "Digitisation",
      "Handwriting & OCR",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "tesseract-ocr",
    "name": "Tesseract OCR",
    "category": "Digitisation, OCR & Accessibility",
    "group": "Digitisation, OCR, Speech & Accessibility",
    "description": "Open-source OCR engine with neural-network (LSTM) recognition, Unicode support and 100+ languages. Outputs plain text, PDF, hOCR, ALTO and other formats.",
    "audiences": [
      "Librarians",
      "Archivists",
      "Digital humanities",
      "Repository staff"
    ],
    "homepageUrl": "https://github.com/tesseract-ocr/tesseract",
    "imageUrl": "https://www.google.com/s2/favicons?domain=github.com&sz=128",
    "accessCode": "OA-1 / Open source",
    "accessLabel": "Open source",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Free and open source (Apache 2.0).",
    "accountRequired": true,
    "integration": "Backend OCR for scanned theses, archival documents and searchable repository PDFs.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "OCR quality depends heavily on scan quality, fonts, scripts and preprocessing. Preserve originals and expose OCR as derived text.",
    "verificationSource": "https://github.com/tesseract-ocr/tesseract",
    "lastVerified": "2026-09-25",
    "tags": [
      "Digitisation",
      "OCR & Accessibility",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "whisper",
    "name": "Whisper",
    "category": "Speech-to-Text & Accessibility",
    "group": "Digitisation, OCR, Speech & Accessibility",
    "description": "Open-source automatic speech-recognition model family released by OpenAI for multilingual transcription and translation-to-English workflows.",
    "audiences": [
      "Librarians",
      "Researchers",
      "Lecturers",
      "Accessibility teams",
      "Oral-history projects"
    ],
    "homepageUrl": "https://github.com/openai/whisper",
    "imageUrl": "https://www.google.com/s2/favicons?domain=github.com&sz=128",
    "accessCode": "OA-1 / Open source",
    "accessLabel": "Open source",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Open-source model/inference code; local use requires suitable compute.",
    "accountRequired": true,
    "integration": "Self-host for lecture, interview, oral-history and accessibility transcription.",
    "integrationTypes": [
      "Self-host"
    ],
    "privacy": "Local / self-hostable",
    "caution": "Transcription errors can alter meaning, names and quotations. Human review is required for research-grade transcripts.",
    "verificationSource": "https://openai.com/index/whisper/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Speech-to-Text & Accessibility",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "lm-studio",
    "name": "LM Studio",
    "category": "Private / Local AI Infrastructure",
    "group": "Private / Local AI Infrastructure",
    "description": "Desktop/server environment for downloading and running local LLMs, chatting with documents offline and exposing local OpenAI-compatible APIs.",
    "audiences": [
      "Researchers",
      "Library IT",
      "Developers",
      "Academic staff"
    ],
    "homepageUrl": "https://lmstudio.ai/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=lmstudio.ai&sz=128",
    "accessCode": "OA-2 / Free local application",
    "accessLabel": "Free local application",
    "accessBadges": [
      "Free Service"
    ],
    "accessText": "Free to use at home and work; local model licensing varies by model.",
    "accountRequired": true,
    "integration": "Useful for desktop pilots and private document Q&A.",
    "integrationTypes": [
      "Desktop"
    ],
    "privacy": "Local / self-hostable",
    "caution": "LM Studio itself is not the same as an open-source model. Check each downloaded model's license and hardware requirements.",
    "verificationSource": "https://lmstudio.ai/blog/free-for-work",
    "lastVerified": "2026-09-25",
    "tags": [
      "Private / Local AI Infrastructure",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "ollama",
    "name": "Ollama",
    "category": "Private / Local AI Infrastructure",
    "group": "Private / Local AI Infrastructure",
    "description": "Runs open-weight language models locally, allowing institutions to keep many AI workloads on their own machines and reduce dependence on external cloud services.",
    "audiences": [
      "Library IT",
      "Researchers",
      "Developers",
      "Privacy-sensitive teams"
    ],
    "homepageUrl": "https://ollama.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=ollama.com&sz=128",
    "accessCode": "OA-1/2 / Free local runtime",
    "accessLabel": "Free local runtime",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Local models are free to run; optional hosted/cloud usage has separate plans.",
    "accountRequired": true,
    "integration": "Strong backend option for a university-hosted AI sandbox or private RAG service.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Local / self-hostable",
    "caution": "Model licenses differ. Local hosting still requires security hardening, compute capacity, monitoring and model-governance policies.",
    "verificationSource": "https://ollama.com/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Private / Local AI Infrastructure",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "open-webui",
    "name": "Open WebUI",
    "category": "Private / Local AI Infrastructure",
    "group": "Private / Local AI Infrastructure",
    "description": "Self-hosted, provider-agnostic web interface for local and cloud AI models, including Ollama and OpenAI-compatible APIs; designed to operate offline if configured that way.",
    "audiences": [
      "Library IT",
      "Developers",
      "Institutional AI teams"
    ],
    "homepageUrl": "https://openwebui.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=openwebui.com&sz=128",
    "accessCode": "OA-1/Conditional / Self-hosted",
    "accessLabel": "Self-hosted",
    "accessBadges": [
      "Open Source / Open Data",
      "Conditional"
    ],
    "accessText": "Self-hostable; current releases include branding/license conditions that must be reviewed for larger deployments.",
    "accountRequired": true,
    "integration": "Potential institution-wide front end for approved AI models and RAG collections.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Local / self-hostable",
    "caution": "Review the current Open WebUI license before deployment, especially branding rules for larger user counts. Configure authentication, RBAC and data retention.",
    "verificationSource": "https://docs.openwebui.com/license/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Private / Local AI Infrastructure",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "google-ai-studio-gemini-api-free-tier",
    "name": "Google AI Studio / Gemini API Free Tier",
    "category": "AI Development & Prototyping",
    "group": "Data Science, Machine Learning & AI Development",
    "description": "Browser-based prototyping environment and developer API for Gemini models, with a free tier on selected models and usage limits.",
    "audiences": [
      "Developers",
      "Information scientists",
      "Research software engineers"
    ],
    "homepageUrl": "https://aistudio.google.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=aistudio.google.com&sz=128",
    "accessCode": "OA-4 / Free developer tier",
    "accessLabel": "Free developer tier",
    "accessBadges": [
      "Free Developer Tier"
    ],
    "accessText": "Free tier available for selected models; higher usage/stronger enterprise data terms require paid configuration.",
    "accountRequired": true,
    "integration": "Useful for prototypes, library assistants and experimental AI features.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Free-tier data-use terms differ from paid enterprise-grade protections. Never embed personal API keys in a client application.",
    "verificationSource": "https://ai.google.dev/gemini-api/docs/billing",
    "lastVerified": "2026-09-25",
    "tags": [
      "AI Development & Prototyping",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "orange-data-mining",
    "name": "Orange Data Mining",
    "category": "Data Science & Machine Learning",
    "group": "Data Science, Machine Learning & AI Development",
    "description": "Open-source visual programming environment for machine learning, data mining and interactive visualisation. Valuable for teaching and low-code exploratory analysis.",
    "audiences": [
      "Researchers",
      "Students",
      "Data librarians",
      "Teaching staff"
    ],
    "homepageUrl": "https://orangedatamining.com/",
    "imageUrl": "https://www.google.com/s2/favicons?domain=orangedatamining.com&sz=128",
    "accessCode": "OA-1 / Open source",
    "accessLabel": "Open source",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Free and open source.",
    "accountRequired": true,
    "integration": "Link-out/download; useful for AI/data-literacy training.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Not a general-purpose generative assistant; include it as an open machine-learning tool for research and teaching.",
    "verificationSource": "https://orangedatamining.com/",
    "lastVerified": "2026-09-25",
    "tags": [
      "Data Science & Machine Learning",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "knime-analytics-platform",
    "name": "KNIME Analytics Platform",
    "category": "Data Science, Machine Learning & GenAI",
    "group": "Data Science, Machine Learning & AI Development",
    "description": "Free and open-source low-code/no-code analytics platform with data connectors, machine learning, text/image analysis and GenAI integrations.",
    "audiences": [
      "Researchers",
      "Information scientists",
      "Data librarians",
      "Academic staff"
    ],
    "homepageUrl": "https://www.knime.com/knime-analytics-platform",
    "imageUrl": "https://www.google.com/s2/favicons?domain=knime.com&sz=128",
    "accessCode": "OA-1/3 / Open-source platform + limited AI assistant",
    "accessLabel": "Open-source platform + limited AI assistant",
    "accessBadges": [
      "Open Source / Open Data"
    ],
    "accessText": "Desktop Analytics Platform is free and open source; optional K-AI has limited free interactions with an account.",
    "accountRequired": true,
    "integration": "Link-out/download; suitable for data-literacy and research-methods support.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Some connectors or remote/automation capabilities may require external accounts or paid KNIME products.",
    "verificationSource": "https://www.knime.com/knime-hub-pricing",
    "lastVerified": "2026-09-25",
    "tags": [
      "Data Science",
      "Machine Learning & GenAI",
      "AI Tools",
      "University Library"
    ]
  },
  {
    "id": "hugging-face-spaces",
    "name": "Hugging Face Spaces",
    "category": "Open AI Model & App Discovery",
    "group": "Data Science, Machine Learning & AI Development",
    "description": "Large directory/hosting environment for interactive AI demos across text, OCR, translation, document analysis, visual QA, data visualisation, speech and other tasks.",
    "audiences": [
      "Researchers",
      "Developers",
      "Information scientists",
      "Teaching staff"
    ],
    "homepageUrl": "https://huggingface.co/spaces",
    "imageUrl": "https://www.google.com/s2/favicons?domain=huggingface.co&sz=128",
    "accessCode": "OA-2/Conditional / Public demos",
    "accessLabel": "Public demos",
    "accessBadges": [
      "Free Service",
      "Conditional"
    ],
    "accessText": "Many Spaces are publicly usable for free; availability and compute quotas vary by individual Space.",
    "accountRequired": true,
    "integration": "Link-out directory; selectively curate trusted Spaces rather than embedding the entire directory.",
    "integrationTypes": [
      "External link"
    ],
    "privacy": "Cloud service",
    "caution": "Spaces are third-party apps with heterogeneous security, licensing, uptime and data practices. Never present all Spaces as institutionally approved.",
    "verificationSource": "https://huggingface.co/spaces",
    "lastVerified": "2026-09-25",
    "tags": [
      "Open AI Model & App Discovery",
      "AI Tools",
      "University Library"
    ]
  }
];
